from django.urls import path
from . import views

urlpatterns = [
    path('doctors/', views.doctor_list, name='doctor'),
    path('doctors/create/', views.create_doctor, name='doctors_create'),
    path('doctors/<int:pk>/', views.show_doctor, name='doctors_show'),
    path('doctors/update/<int:pk>/', views.doctors_update, name='doctors_update'),
    path('doctors/disable/<int:pk>/', views.doctors_disable, name='doctors_disable'),
    path('doctors/delete/<int:pk>/', views.doctors_delete, name='doctors_delete'),
    path('typeappointments/', views.typeappointment_list, name='typeappointment'),
    path('typeappointments/create/', views.create_typeappointment, name='typeappointments_create'),
    path('typeappointments/<int:pk>/', views.typeappointment_show, name='typeappointments_show'),
    path('typeappointments/update/<int:pk>/', views.typeappointments_update, name='typeappointments_update'),
    path('typeappointments/disable/<int:pk>/', views.typeappointments_disable, name='typeappointments_disable'),
    path('typeappointments/delete/<int:pk>/', views.typeappointments_delete, name='typeappointments_delete'),
    path('priorityappointments/', views.priorityappointment_list, name='priorityappointment'),
    path('priorityappointments/create/', views.create_priorityappointment, name='priorityappointments_create'),
    path('priorityappointments/<int:pk>/', views.priorityappointment_show, name='priorityappointments_show'),
    path('priorityappointments/update/<int:pk>/', views.priorityappointments_update, name='priorityappointments_update'),
    path('priorityappointments/disable/<int:pk>/', views.priorityappointments_disable, name='priorityappointments_disable'),
    path('priorityappointments/delete/<int:pk>/', views.priorityappointments_delete, name='priorityappointments_delete'),
    path('categorymedicalrecords/', views.categorymedicalrecord_list, name='categorymedicalrecord'),
    path('categorymedicalrecords/create/', views.create_categorymedicalrecord, name='categorymedicalrecords_create'),
    path('categorymedicalrecords/<int:pk>/', views.categorymedicalrecord_show, name='categorymedicalrecords_show'),
    path('categorymedicalrecords/update/<int:pk>/', views.categorymedicalrecords_update, name='categorymedicalrecords_update'),
    path('categorymedicalrecords/disable/<int:pk>/', views.categorymedicalrecords_disable, name='categorymedicalrecords_disable'),
    path('categorymedicalrecords/delete/<int:pk>/', views.categorymedicalrecords_delete, name='categorymedicalrecords_delete'),
    path('patients/', views.patient_list, name='patient'),
    path('patients/create/', views.create_patient, name='patients_create'),
    path('patients/<int:pk>/', views.patient_show, name='patients_show'),
    path('patients/update/<int:pk>/', views.patients_update, name='patients_update'),
    path('patients/disable/<int:pk>/', views.patients_disable, name='patients_disable'),
    path('patients/delete/<int:pk>/', views.patients_delete, name='patients_delete'),
    path('patientrecords/', views.patientrecord_list, name='patientrecord'),
    path('patientrecords/create/', views.create_patientrecord, name='patientrecords_create'),
    path('patientrecords/<int:pk>/', views.patientrecord_show, name='patientrecords_show'),
    path('patientrecords/update/<int:pk>/', views.patientrecords_update, name='patientrecords_update'),
    path('patientrecords/disable/<int:pk>/', views.patientrecords_disable, name='patientrecords_disable'),
    path('patientrecords/delete/<int:pk>/', views.patientrecords_delete, name='patientrecords_delete'),
    path('medicalappointments/', views.medicalappointment_list, name='medicalappointment'),
    path('medicalappointments/create/', views.create_medicalappointment, name='medicalappointments_create'),
    path('medicalappointments/<int:pk>/', views.medicalappointment_show, name='medicalappointments_show'),
    path('medicalappointments/update/<int:pk>/', views.medicalappointments_update, name='medicalappointments_update'),
    path('medicalappointments/disable/<int:pk>/', views.medicalappointments_disable, name='medicalappointments_disable'),
    path('medicalappointments/delete/<int:pk>/', views.medicalappointments_delete, name='medicalappointments_delete'),
    path('medicalrecords/', views.medicalrecord_list, name='medicalrecord'),
    path('medicalrecords/create/', views.create_medicalrecord, name='medicalrecords_create'),
    path('medicalrecords/<int:pk>/', views.medicalrecord_show, name='medicalrecords_show'),
    path('medicalrecords/update/<int:pk>/', views.medicalrecords_update, name='medicalrecords_update'),
    path('medicalrecords/disable/<int:pk>/', views.medicalrecords_disable, name='medicalrecords_disable'),
    path('medicalrecords/delete/<int:pk>/', views.medicalrecords_delete, name='medicalrecords_delete'),
    path('hello_world/', views.hello_world),
    path('', views.dashboard, name='dashboard'),
]
