# Generated by Django 5.2.5 on 2026-05-15 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryMedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Categoría de Expediente',
                'verbose_name_plural': 'Categorías de Expediente',
                'db_table': 'category_medical_records',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(blank=True, max_length=50, null=True)),
                ('first_lastname', models.CharField(max_length=100)),
                ('second_lastname', models.CharField(blank=True, max_length=100, null=True)),
                ('identity_id', models.CharField(max_length=15, unique=True)),
                ('gender', models.BooleanField()),
                ('phone_number', models.CharField(max_length=15)),
                ('specialty', models.TextField()),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctores',
                'db_table': 'doctors',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(blank=True, max_length=50, null=True)),
                ('first_lastname', models.CharField(max_length=100)),
                ('second_lastname', models.CharField(blank=True, max_length=100, null=True)),
                ('identity_id', models.CharField(max_length=15, unique=True)),
                ('birth_date', models.DateField()),
                ('gender', models.BooleanField()),
                ('phone_number', models.CharField(max_length=15)),
                ('mobile_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('blood_group', models.CharField(max_length=8)),
                ('name_emergency_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name_emergency_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number_emergency_contact', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'db_table': 'patients',
            },
        ),
        migrations.CreateModel(
            name='PriorityAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Prioridad de Cita',
                'verbose_name_plural': 'Prioridades de Cita',
                'db_table': 'priority_appointments',
            },
        ),
        migrations.CreateModel(
            name='TypeAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Cita',
                'verbose_name_plural': 'Tipos de Cita',
                'db_table': 'type_appointments',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='PatientRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('entry_date', models.DateField()),
                ('id_patient', models.ForeignKey(db_column='id_patient', on_delete=django.db.models.deletion.PROTECT, related_name='records', to='citas.patient')),
            ],
            options={
                'verbose_name': 'Expediente de Paciente',
                'verbose_name_plural': 'Expedientes de Paciente',
                'db_table': 'patient_records',
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='id_patient_record',
            field=models.ForeignKey(blank=True, db_column='id_patient_record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_patient', to='citas.patientrecord'),
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.PROTECT, related_name='medical_records', to='citas.categorymedicalrecord')),
                ('id_patient_record', models.ForeignKey(db_column='id_patient_record', on_delete=django.db.models.deletion.PROTECT, related_name='medical_records', to='citas.patientrecord')),
            ],
            options={
                'verbose_name': 'Registro Médico',
                'verbose_name_plural': 'Registros Médicos',
                'db_table': 'medical_records',
            },
        ),
        migrations.CreateModel(
            name='MedicalAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('appointment_time', models.DateTimeField()),
                ('reason_appointment', models.TextField()),
                ('cancellation_date', models.DateTimeField(blank=True, null=True)),
                ('reason_for_cancellation', models.TextField(blank=True, null=True)),
                ('rescheduled_date', models.DateTimeField(blank=True, null=True)),
                ('patient_comments', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('id_doctor', models.ForeignKey(db_column='id_doctor', on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='citas.doctor')),
                ('patient_record', models.ForeignKey(db_column='patient_record_id', on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='citas.patientrecord')),
                ('priority_id', models.ForeignKey(db_column='priority_id', on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='citas.priorityappointment')),
                ('type_id', models.ForeignKey(db_column='type_id', on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='citas.typeappointment')),
            ],
            options={
                'verbose_name': 'Cita Médica',
                'verbose_name_plural': 'Citas Médicas',
                'db_table': 'medical_appointments',
            },
        ),
    ]
